name: ci 

on:

  push:
    branches: ["main"]
  pull_request:
    branches: [ "*" ]

jobs:

  deploy-recipe-with-action:
    name: deploy-recipe-with-action
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: deploy test recipe
        uses: "pangeo-forge/deploy-recipe-action@v0.2"
        with:
          #select_recipe_by_label: ""
          pangeo_forge_runner_config: "./config/local.json"

  deploy-recipe-manually:
    name: deploy-recipe-manually
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -r feedstock/requirements.txt
          pip install pangeo-forge-runner
      - name: deploy test recipe
        run: pangeo-forge-runner bake --repo=. -f=config/local.json --Bake.recipe_id=euro-cordex --Bake.job_name=test --prune 
