name: ci 

on:
  push:
    branches: ["main"]
  pull_request:
    branches: [ "*" ]

jobs:
  deploy-recipes:
    name: deploy-recipes
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: "Deploy test recipe"
        uses: "pangeo-forge/deploy-recipe-action@v0.2"
        with:
          #select_recipe_by_label: ""
          pangeo_forge_runner_config: "./config/local.json"
